return {
    ["Main"] = "Menu Principal",
    ["Misc"] = "Miscelâneas",
    ["UI Settings"] = "Configurações",

    ["Auto working"] = "Auto Farm",
    ["Esp"] = "ESP",
    ["Teleport"] = "Teleporte",

    ["Auto Check Npc"] = "Auto Verificar NPC",
    ["Auto Treat"] = "Auto Curar",
    ["Auto Stamp Fire Room"] = "Auto Apagar Fogo da Sala",
    ["Auto Stamp Fire Npc"] = "Auto Apagar Fogo do NPC",
    ["Auto Ask Npc Leave"] = "Auto Expulsar NPC",
    ["Auto Clean Smile"] = "Auto Limpar Slime",
    ["Auto Fix Camera"] = "Auto Consertar Câmera",
    ["Auto Barney"] = "Auto Café para o Barney",
    ["Auto Taser NPC"] = "Auto Taser no NPC",
    ["Taser Npc"] = "Usar Taser no NPC",
    ["Help Npc Interrupted"] = "Priorizar Resgate",
    ["Auto Help Npc Interrupted"] = "Auto Salvar NPC Interrompido",

    ["Esp Npc"] = "ESP NPC",
    ["Esp Player"] = "ESP Jogadores",
    ["Esp Item"] = "ESP Itens",

    ["Goto Spawn"] = "Ir para o Spawn",
    ["Instant Prompt"] = "Prompt Instantâneo",
    ["Prompt Reach"] = "Alcançar Prompt de Longe",
    ["Unlock Person"] = "Desbloquear Câmera",
    ["Auto Collect Coffee"] = "Auto Coletar Café",
    ["Auto Monster Bed"] = "Auto Espantar Monstro da Cama",

    ["Remove Door"] = "Remover Todas as Portas",
    ["Inf Stanity"] = "Sanidade Infinita",
}