return {
    ["Main"] = "Главное",
    ["Misc"] = "Разное",
    ["UI Settings"] = "Настройки интерфейса",

    ["Auto working"] = "Авто-фарм",
    ["Esp"] = "ESP",
    ["Teleport"] = "Телепорт",

    ["Auto Check Npc"] = "Авто-проверка NPC",
    ["Auto Treat"] = "Авто-лечение",
    ["Auto Stamp Fire Room"] = "Авто-тушение комнат",
    ["Auto Stamp Fire Npc"] = "Авто-тушение NPC",
    ["Auto Ask Npc Leave"] = "Авто-выгонять NPC",
    ["Auto Clean Smile"] = "Авто-очистка слизи",
    ["Auto Fix Camera"] = "Авто-починка камер",
    ["Auto Barney"] = "Авто-кофе для Барни",
    ["Auto Taser NPC"] = "Авто-шокер для NPC",
    ["Taser Npc"] = "Ударить NPC шокером",
    ["Help Npc Interrupted"] = "Приоритет спасения",
    ["Auto Help Npc Interrupted"] = "Авто-спасение прерванных NPC",

    ["Esp Npc"] = "ESP на NPC",
    ["Esp Player"] = "ESP на игроков",
    ["Esp Item"] = "ESP на предметы",

    ["Goto Spawn"] = "На спавн",
    ["Instant Prompt"] = "Мгновенное действие",
    ["Prompt Reach"] = "Длинный Prompt",
    ["Unlock Person"] = "Разблокировать камеру",
    ["Auto Collect Coffee"] = "Авто-сбор кофе",
    ["Auto Monster Bed"] = "Авто-прогнать монстра из кровати",

    ["Remove Door"] = "Удалить все двери",
    ["Inf Stanity"] = "Бесконечный рассудок",
}