return {
    ["Main"] = "Menu",
    ["Misc"] = "Lặt Vặt",
    ["UI Settings"] = "Tùy Chỉnh",

    ["Auto working"] = "Auto Cày",
    ["Esp"] = "Soi",
    ["Teleport"] = "Dịch Chuyển",

    ["Auto Check Npc"] = "Auto kiểm tra Npc",
    ["Auto Treat"] = "Auto Chữa",
    ["Auto Stamp Fire Room"] = "Auto Dập Lửa",
    ["Auto Stamp Fire Npc"] = "Auto Cứu Cháy",
    ["Auto Ask Npc Leave"] = "Auto Đuổi NPC (Đạp Kính)",
    ["Auto Clean Smile"] = "Auto Lau Slime",
    ["Auto Fix Camera"] = "Auto Sửa Camera",
    ["Auto Barney"] = "Auto Cho Cafe Barney",
    ["Auto Taser NPC"] = "Auto Chích Điện",
    ["Help Npc Interrupted"] = "Ưu Tiên Cứu Khi Ngắt",
    ["Auto Help Npc Interrupted"] = "Auto Gánh Npc",

    ["Esp Npc"] = "Soi NPC",
    ["Esp Player"] = "Soi Player",
    ["Esp Item"] = "Soi Đồ Cứu",

    ["Goto Spawn"] = "Về Spawn",
    ["Instant Prompt"] = "Lập tức Prompt",
    ["Prompt Reach"] = "Prompt Xa",
    ["Unlock Person"] = "Mở Góc Camera",
    ["Auto Collect Coffee"] = "Auto Húp Cafe",
    ["Auto Monster Bed"] = "Auto Đuổi Monster Bed",

    ["Remove Door"] = "Xóa Tất Cả Cửa",
    ["Inf Stanity"] = "Hack Não",
}
